name: Update Release Yaml

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Name of the artifact to update in application.yml'
        required: true
        type: string
      artifact_version:
        description: 'Artifact version to set in application.yml'
        required: true
        type: string
      artifact_buildnumber:
        description: 'Artifact buildnumber to set in application.yml'
        required: false
        type: string

jobs:
  update-application-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: 'Hello World'
        run: |
          echo "I am here!"
          echo "Inputs are: ${{inputs.artifact_name}} : ${{inputs.artifact_version}} (${{inputs.artifact_buildnumber}})"

      - name: 'Checkout Source Code'
        uses: actions/checkout@v3

      - name: 'Install yq - portable yaml processor'
        uses: mikefarah/yq@v4.35.2

      - name: 'Update application.yml'
        run: |
          yq  -i '.${{inputs.artifact_name }}.version = "${{inputs.artifact_version}}"' application.yaml
          cat application.yaml

      - name: 'Commit and push changes'
        uses: EndBug/add-and-commit@v9
        with:
          add: application.yaml
